name: Build and push image
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: "read"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  go-version:
    outputs:
      go-version: ${{ steps.go-version.outputs.go-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4.0.1
      - id: go-version
        run: echo "go-version=$(mise current go)" >> $GITHUB_OUTPUT
  checks:
    strategy:
      fail-fast: false
      matrix:
        mise-task:
          - check:deadcode
          - check:golangci-lint
          - check:gosec
          - check:govet
          - check:govulncheck
          - check:ratchet
          - check:staticcheck
          - ci:fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4.0.1
      - run: mise run ${{ matrix.mise-task }}
  branch-protection-checkpoint:
    needs:
      - checks
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.checks.result != 'success' }}
        run: exit 1
      - run: echo "All checks and builds passed."
  build_and_push:
    if: github.ref == 'refs/heads/main'
    needs:
      - go-version
      - branch-protection-checkpoint
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      RUNNER_IMG: "gcr.io/distroless/static-debian12:nonroot"
      BASEIMG_IDENTITY: "keyless@distroless.iam.gserviceaccount.com"
      BASEIMG_ISSUER: "https://accounts.google.com"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # ratchet:sigstore/cosign-installer@v4.1.2
      - run: cosign verify --certificate-identity ${{ env.BASEIMG_IDENTITY }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.RUNNER_IMG }}
      - uses: nais/platform-build-push-sign@df590279b21bc5978519685752f9eaddd546043c # ratchet:nais/platform-build-push-sign@main
        id: build_push_sign
        with:
          name: console-github-auth
          build_args: |
            GO_VERSION=${{ needs.go-version.outputs.go-version }}
          google_service_account: gh-console-github-auth
          push: ${{ github.actor != 'dependabot[bot]' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}

